# Rust code formatting configuration
# Run with: cargo fmt

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 80
